sudo: required

language: node_js
node_js: 
  - "9.10.1"
cache: npm

services:
  - docker

script:
  - docker build --tag nodedock .
  - docker run nodedock npm test

after_script:
  - sh deployment/now.sh